In [ ]:
import pandas as pd
import numpy
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,r2_score


#Used Models
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor

In [ ]:
symbol='^NSEI'
ticker = yf.Ticker(symbol)
data=ticker.history(period='60d',interval='5m')
data.reset_index(inplace=True)

In [ ]:
# data = pd.read_csv('/content/Nifty50_shortTerm_5m_New.csv')

print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4420 entries, 0 to 4419
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype                       
---  ------        --------------  -----                       
 0   Datetime      4420 non-null   datetime64[ns, Asia/Kolkata]
 1   Open          4420 non-null   float64                     
 2   High          4420 non-null   float64                     
 3   Low           4420 non-null   float64                     
 4   Close         4420 non-null   float64                     
 5   Volume        4420 non-null   int64                       
 6   Dividends     4420 non-null   float64                     
 7   Stock Splits  4420 non-null   float64                     
dtypes: datetime64[ns, Asia/Kolkata](1), float64(6), int64(1)
memory usage: 276.4 KB
None


In [ ]:
print(data.describe())


               Open          High           Low         Close  Volume  \
count   4420.000000   4420.000000   4420.000000   4420.000000  4420.0   
mean   21161.827875  21170.879788  21152.350855  21161.873960     0.0   
std      735.323841    736.854692    733.314341    735.093211     0.0   
min    19609.650391  19620.650391  19580.449219  19609.650391     0.0   
25%    20867.524902  20875.862305  20860.000488  20867.287598     0.0   
50%    21455.025391  21465.174805  21446.924805  21455.399414     0.0   
75%    21700.375488  21709.849609  21689.912109  21699.612305     0.0   
max    22118.000000  22125.849609  22112.050781  22118.750000     0.0   

       Dividends  Stock Splits  
count     4420.0        4420.0  
mean         0.0           0.0  
std          0.0           0.0  
min          0.0           0.0  
25%          0.0           0.0  
50%          0.0           0.0  
75%          0.0           0.0  
max          0.0           0.0  


In [ ]:
data.drop_duplicates()

Datetime          Open          High           Low  \
0    2023-11-15 09:15:00+05:30  19651.400391  19651.400391  19580.449219   
1    2023-11-15 09:20:00+05:30  19613.349609  19620.650391  19607.050781   
2    2023-11-15 09:25:00+05:30  19609.650391  19629.250000  19609.599609   
3    2023-11-15 09:30:00+05:30  19628.500000  19639.949219  19626.050781   
4    2023-11-15 09:35:00+05:30  19629.500000  19633.949219  19623.250000   
...                        ...           ...           ...           ...   
4415 2024-02-09 15:05:00+05:30  21780.800781  21795.199219  21774.300781   
4416 2024-02-09 15:10:00+05:30  21790.150391  21800.349609  21780.349609   
4417 2024-02-09 15:15:00+05:30  21783.949219  21790.199219  21777.099609   
4418 2024-02-09 15:20:00+05:30  21777.650391  21784.400391  21772.500000   
4419 2024-02-09 15:25:00+05:30  21781.349609  21787.250000  21773.750000   

             Close  Volume  Dividends  Stock Splits  
0     19613.650391       0        0.0           0.0  
1     19609.650391       0        0.0           0.0  
2     19628.650391       0        0.0           0.0  
3     19629.000000       0        0.0           0.0  
4     19627.500000       0        0.0           0.0  
...            ...     ...        ...           ...  
4415  21789.300781       0        0.0           0.0  
4416  21782.800781       0        0.0           0.0  
4417  21777.900391       0        0.0           0.0  
4418  21780.849609       0        0.0           0.0  
4419  21786.000000       0        0.0           0.0  

[4420 rows x 8 columns]

In [ ]:
data.isnull().sum()

Datetime        0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64

In [ ]:
data.drop(['Datetime','Volume','Dividends','Stock Splits'],axis=1,inplace=True)
data.head(10)


Open          High           Low         Close
0  19651.400391  19651.400391  19580.449219  19613.650391
1  19613.349609  19620.650391  19607.050781  19609.650391
2  19609.650391  19629.250000  19609.599609  19628.650391
3  19628.500000  19639.949219  19626.050781  19629.000000
4  19629.500000  19633.949219  19623.250000  19627.500000
5  19627.800781  19630.000000  19621.300781  19623.800781
6  19624.449219  19635.099609  19623.150391  19627.949219
7  19627.250000  19632.599609  19622.349609  19624.099609
8  19624.099609  19634.949219  19622.500000  19633.300781
9  19633.050781  19637.300781  19630.000000  19631.800781

from matplotlib import pyplot as plt
_df_16['Open'].plot(kind='hist', bins=20, title='Open')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_17['High'].plot(kind='hist', bins=20, title='High')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_18['Low'].plot(kind='hist', bins=20, title='Low')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_19['Close'].plot(kind='hist', bins=20, title='Close')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_20.plot(kind='scatter', x='Open', y='High', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_21.plot(kind='scatter', x='High', y='Low', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_22.plot(kind='scatter', x='Low', y='Close', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_23['Open'].plot(kind='line', figsize=(8, 4), title='Open')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_24['High'].plot(kind='line', figsize=(8, 4), title='High')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_25['Low'].plot(kind='line', figsize=(8, 4), title='Low')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_26['Close'].plot(kind='line', figsize=(8, 4), title='Close')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
X=data.drop(['Close'],axis=1)
print(X)
y=data['Close']


              Open          High           Low
0     19651.400391  19651.400391  19580.449219
1     19613.349609  19620.650391  19607.050781
2     19609.650391  19629.250000  19609.599609
3     19628.500000  19639.949219  19626.050781
4     19629.500000  19633.949219  19623.250000
...            ...           ...           ...
4415  21780.800781  21795.199219  21774.300781
4416  21790.150391  21800.349609  21780.349609
4417  21783.949219  21790.199219  21777.099609
4418  21777.650391  21784.400391  21772.500000
4419  21781.349609  21787.250000  21773.750000

[4420 rows x 3 columns]


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:

my_model = XGBRegressor()
my_model.fit(1X_train, y_train)

predictions = my_model.predict(X_test)
print("Mean Absolute Error: " + str(mean_absolute_error(predictions, y_test)))

print("R2 Score" + str(r2_score(y_test,predictions)))


print("Accuracy Score : "+str(my_model.score(X_test,y_test)))

predictions


Mean Absolute Error: 6.043443774745475
R2 Score0.9998321236329427
Accuracy Score : 0.9998321236329427


array([21740.875, 21574.602, 21280.617, 19912.588, 21468.572, 21680.281,
       21681.383, 19781.4  , 21965.545, 20264.871, 20263.81 , 19758.553,
       21905.6  , 21667.969, 21457.303, 20645.992, 21165.3  , 21258.154,
       20741.775, 19680.162, 21663.143, 21760.662, 19735.781, 21315.48 ,
       19775.312, 21026.016, 21615.668, 19808.475, 19813.42 , 19849.611,
       21660.578, 21560.826, 20910.316, 19912.588, 21918.855, 21442.52 ,
       21606.14 , 19775.357, 21694.818, 21298.729, 21381.084, 21625.521,
       21268.37 , 21634.494, 21945.52 , 21543.281, 21619.117, 21541.354,
       21760.588, 20932.361, 21450.693, 21340.91 , 21406.557, 21646.328,
       21434.957, 21938.354, 20521.664, 21918.62 , 21689.715, 21538.812,
       21932.25 , 21008.107, 21443.111, 22021.598, 21737.766, 21575.537,
       21583.12 , 21187.562, 20003.064, 21391.072, 21694.406, 20927.1  ,
       21177.756, 21734.402, 19740.719, 21371.994, 21790.842, 21705.393,
       20813.87 , 21781.842, 21748.79 , 21435.69 , 

In [ ]:
RandomeForestModel = RandomForestRegressor()
RandomeForestModel.fit(X_train, y_train)


predictions = RandomeForestModel.predict(X_test)
print("Mean Absolute Error: " + str(mean_absolute_error(predictions, y_test)))

print("R2 Score" + str(r2_score(y_test,predictions)))


print("Accuracy Score : "+str(RandomeForestModel.score(X_test,y_test)))

predictions

Mean Absolute Error: 5.155476239925043
R2 Score0.9998665933275134
Accuracy Score : 0.9998665933275134


array([21741.08353516, 21574.06236328, 21276.90337891, 19877.65935547,
       21467.87664062, 21680.50234375, 21682.10041016, 19779.05164062,
       21964.51738281, 20261.66451172, 20260.86611328, 19761.59027344,
       21904.77607422, 21671.52431641, 21460.82966797, 20640.55853516,
       21165.20552734, 21256.98076172, 20776.04119141, 19681.84113281,
       21661.24806641, 21757.32609375, 19736.65013672, 21317.86427734,
       19775.334375  , 21023.28830078, 21612.63955078, 19808.27957031,
       19813.66521484, 19857.62384766, 21659.53212891, 21559.346875  ,
       20909.27253906, 19871.55488281, 21919.13373047, 21444.63929688,
       21603.68054687, 19775.85816406, 21695.35595703, 21304.24019531,
       21376.80023438, 21624.83521484, 21259.91257813, 21624.37697266,
       21942.03871094, 21546.60740234, 21617.51066406, 21542.66068359,
       21759.10064453, 20924.31060547, 21450.73074219, 21336.52970703,
       21398.27835937, 21645.33873047, 21436.17677734, 21940.79630859,
      

In [ ]:
DesitionTreeModel = DecisionTreeRegressor()
DesitionTreeModel.fit(X_train, y_train)


predictions = DesitionTreeModel.predict(X_test)
print("Mean Absolute Error: " + str(mean_absolute_error(predictions, y_test)))

print("R2 Score" + str(r2_score(y_test,predictions)))


print("Accuracy Score : "+str(DesitionTreeModel.score(X_test,y_test)))

predictions

Mean Absolute Error: 6.277166996606335
R2 Score0.999792347117128
Accuracy Score : 0.999792347117128


array([21742.09960938, 21571.84960938, 21283.65039062, 19876.05078125,
       21468.69921875, 21682.34960938, 21685.05078125, 19778.30078125,
       21965.34960938, 20259.75      , 20262.90039062, 19761.84960938,
       21903.40039062, 21667.75      , 21462.09960938, 20634.15039062,
       21167.15039062, 21248.75      , 20777.09960938, 19682.90039062,
       21665.75      , 21751.25      , 19726.15039062, 21320.40039062,
       19770.80078125, 21021.55078125, 21609.80078125, 19810.69921875,
       19813.05078125, 19858.80078125, 21659.80078125, 21562.05078125,
       20914.40039062, 19876.05078125, 21911.40039062, 21444.19921875,
       21602.34960938, 19774.65039062, 21698.90039062, 21305.44921875,
       21379.5       , 21633.19921875, 21260.        , 21633.        ,
       21944.69921875, 21547.15039062, 21612.69921875, 21540.15039062,
       21752.59960938, 20921.34960938, 21447.19921875, 21328.90039062,
       21403.09960938, 21643.5       , 21434.80078125, 21937.84960938,
      

In [ ]:

import pickle

pickle.dump(my_model,open('/content/drive/MyDrive/AI COLLAGE/5m_Nifty_XGBoost.pkl','wb'))

In [ ]:

import pickle

pickle.dump(my_model,open('/content/drive/MyDrive/AI COLLAGE/5m_Nifty_RandomForestRegressor.pkl','wb'))

In [ ]:

import pickle

pickle.dump(my_model,open('/content/drive/MyDrive/AI COLLAGE/5m_Nifty_DesicionTreeModel.pkl','wb'))

In [ ]:

import yfinance as yf
import datetime as dt
import pickle
from sklearn.metrics import mean_absolute_error,r2_score,accuracy


# Load the model from the pickle file
with open('/content/drive/MyDrive/AI COLLAGE/5m_Nifty_RandomForestRegressor.pkl', 'rb') as f:
    Rand = pickle.load(f)


with open('/content/drive/MyDrive/AI COLLAGE/5m_Nifty_DesicionTreeModel.pkl', 'rb') as f:
    Decision = pickle.load(f)


with open('/content/drive/MyDrive/AI COLLAGE/5m_Nifty_XGBoost.pkl', 'rb') as f:
    XgBoostModel = pickle.load(f)



/usr/local/lib/python3.10/dist-packages/yfinance/base.py:48: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  _empty_series = pd.Series()


ImportError: cannot import name 'accuracy' from 'sklearn.metrics' (/usr/local/lib/python3.10/dist-packages/sklearn/metrics/__init__.py)

In [ ]:
while True:
    ticker = yf.Ticker('^NSEI')
    start=dt.datetime.now().strftime('%Y-%m-%d')
    end=(dt.datetime.now() + dt.timedelta(days=1)).strftime('%Y-%m-%d')

    data = ticker.history(interval='5m',start=start,end=end)
    data.reset_index(inplace=True)
    # print(data)
    data.columns = data.columns.str.strip()  # Remove extra spaces from column names

    data.drop(['Datetime', 'Volume', 'Dividends', 'Stock Splits'], inplace=True, axis=1)
    y = data['Close'].copy()
    data.drop(['Close'], inplace=True, axis=1)

    print("Random Forest Regressor")
    print("---------------------------\n")
    Rand_predic=Rand.predict(data)
    last_pred=Rand_predic[-1]
    print(f'Last Prediction ----------> :{ last_pred}')
    print(f'mae : {mean_absolute_error(y,Rand_predic)}')
    # print(f"Rand Accuracy Score :{}")
    print(f'r2 : {r2_score(y,Rand_predic)}')
    print("---------------------------")
    print("\n\n\n")

    print("Desicion Tree Regressor")
    print("---------------------------\n")
    DecisionPred=Decision.predict(data)
    last_pred=DecisionPred[-1]
    mae=mean_absolute_error(y,DecisionPred)
    # last_pred=last_pred+mae
    print(f'Last Prediction ----------> :{ last_pred}')
    print(f'mae : {mae}')
    print(f'r2 : {r2_score(y,DecisionPred)}')
    print("---------------------------")
    print("\n\n\n")

    print("XgBoostModel ")
    print("---------------------------\n")
    XgBoostPred=XgBoostModel.predict(data)
    last_pred=XgBoostPred[-1]
    print(f'Last Prediction ----------> :{ last_pred}')
    print(f'mae : {mean_absolute_error(y,XgBoostPred)}')
    print(f'r2 : {r2_score(y,XgBoostPred)}')
    print("---------------------------")
    print("\n\n\n")
    # data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
